name: todolist_cicd
on:
  push:
    branches: [main]
jobs:
  todolist_cicd:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4 # Checkout the repository
      - name: Copy source code to another folder
      run: cp -r ./* /projects/todolist
