name: todolist_cicd
on:
  push:
     branches: [main]
jobs:
  todolist_cicd:
     runs-on: self-hosted
     steps:
       - uses: actions/checkout@v2
       - run: cp -rf * /projects/todolist/
       - run: cd /projects/todolist/
       - run: pwd  
       
