name: todolist_cicd
on:
  push:
    branches: [main]
jobs:
   todolist_cicd:
     runs-on: self-hosted
     steps:
       - uses: actions/checkout@v4
       - name: copy code
         run: |
           sudo cp -rf /home/itadmin/actions-runner/_work/todolist/todolist/* /github/github_action/todolist
         
        
